# Generated by Django 3.2.7 on 2021-09-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_file_filecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='file',
            name='fileDescription',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='file',
            name='lastUploadBy',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
