# Generated by Django 3.2.7 on 2021-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_date_file_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileContent',
            field=models.CharField(max_length=200),
        ),
    ]
