# Generated by Django 3.2.7 on 2021-09-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_fileblob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileContent',
            field=models.FilePathField(max_length=200),
        ),
    ]
