# Generated by Django 3.2.7 on 2021-09-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_alter_file_filecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileContent',
            field=models.FileField(upload_to='search/FilesForBlob'),
        ),
    ]
