# Generated by Django 3.2.7 on 2021-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_file_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fileContent',
            field=models.FileField(upload_to=''),
        ),
    ]
